--- #YAML:1.0
name: Device-Ericsson-AccessoryMenu
version: 0.8
author:
  - Richard Clamp <richardc@unixbeard.net>
abstract: allows use of a T68i as a remote control
license: perl
requires:
  Class::Accessor::Fast: 0
  Test::More: 0
recommends:
  Device::SerialPort: 0
provides:
  Device::Ericsson::AccessoryMenu:
    file: lib/Device/Ericsson/AccessoryMenu.pm
    version: 0.8
  Device::Ericsson::AccessoryMenu::Menu:
    file: lib/Device/Ericsson/AccessoryMenu/Menu.pm
  Device::Ericsson::AccessoryMenu::Mouse:
    file: lib/Device/Ericsson/AccessoryMenu/Mouse.pm
  Device::Ericsson::AccessoryMenu::Slider:
    file: lib/Device/Ericsson/AccessoryMenu/Slider.pm
  Device::Ericsson::AccessoryMenu::State:
    file: lib/Device/Ericsson/AccessoryMenu/State.pm
  Device::Ericsson::AccessoryMenu::Text:
    file: lib/Device/Ericsson/AccessoryMenu/Text.pm
generated_by: Module::Build version 0.23
